server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news_feed
    username: postgres
    password: postgres
    initialization-mode: always
    schema: classpath:/schema.sql
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB




